// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unaryMath.proto

package grpc.examples.unarymath;

public interface CalculateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:math.CalculateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
