// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unaryMath.proto

package grpc.examples.unarymath;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:math.Empty)
    com.google.protobuf.MessageOrBuilder {
}
