// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unaryMath.proto

package grpc.examples.unarymath;

public final class MathServiceImpl {
  private MathServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_math_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_math_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_math_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_math_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_math_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_math_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_math_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_math_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017unaryMath.proto\022\004math\"\037\n\020CalculateRequ" +
      "est\022\013\n\003val\030\001 \001(\t\" \n\021CalculateResponse\022\013\n" +
      "\003val\030\001 \001(\t\"U\n\007Message\022\"\n\006detail\030\001 \001(\0162\022." +
      "math.Message.Enum\"&\n\004Enum\022\013\n\007UNKNOWN\020\000\022\007" +
      "\n\003LOW\020\001\022\010\n\004HIGH\020\002\"\007\n\005Empty2t\n\013MathServic" +
      "e\022>\n\tcalculate\022\026.math.CalculateRequest\032\027" +
      ".math.CalculateResponse\"\000\022%\n\005empty\022\r.mat" +
      "h.Message\032\013.math.Empty\"\000B,\n\027grpc.example" +
      "s.unarymathB\017MathServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_math_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_math_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_math_CalculateRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_math_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_math_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_math_CalculateResponse_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_math_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_math_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_math_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_math_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_math_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_math_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
