// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unaryMath.proto

package grpc.examples.unarymath;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:math.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.math.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.math.Message.Enum detail = 1;</code>
   */
  grpc.examples.unarymath.Message.Enum getDetail();
}
